#!/bin/sh

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "chronos:$(openssl passwd -1)" > /mnt/stateful_partition/etc/devmode.passwd
