# Copyright 2023 The ChromiumOS Authors
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file or at
# https://developers.google.com/open-source/licenses/bsd

RUSTFLAGS='-C target-feature=+crt-static'

.PHONY : build
build:
	@rustup -q which rustc > /dev/null || { echo "Please install rustup via https://rustup.rs/" ; exit 1 ; }
	RUSTFLAGS=$(RUSTFLAGS) cargo build --target x86_64-unknown-linux-gnu
	make doc

.PHONY : doc
doc: docs/cmdline.md

.PHONY : release_build
release_build:
	@rustup -q which rustc > /dev/null || { echo "Please install rustup via https://rustup.rs/" ; exit 1 ; }
	RUSTFLAGS=$(RUSTFLAGS) cargo build --release --target x86_64-unknown-linux-gnu

.PHONY : install
install:
	@rustup -q which rustc > /dev/null || { echo "Please install rustup via https://rustup.rs/" ; exit 1 ; }
	RUSTFLAGS=$(RUSTFLAGS) cargo install --target x86_64-unknown-linux-gnu --path .
	@echo $$SHELL | grep bash > /dev/null && cro3 setup bash-completion || echo "SHELL is not Bash. Command completion will not work."
	@printf "\ncro3 is successfully installed at `which cro3`. Try \`cro3 --help\` if you want!\n"

.PHONY : check
check:
	cargo fmt
	cargo clippy -- -D warnings
	cargo test
	cargo check

.PHONY : commit
commit:
	make check
	git add -A
	git commit

.PHONY : test
test:
	cargo test

.PHONY : release
release:
	bash scripts/deploy_release.sh

DOC_SRC=$(shell git ls-files src/cmd/*.rs)
docs/cmdline.md: ${DOC_SRC} Makefile
	@echo '<!--' > $@
	@echo 'This file is automatically generated on `make`.' >> $@
	@echo 'Please modify src/cmd/*.rs files and rebuild lium to update.' >> $@
	@echo '-->' >> $@
	@cat ${DOC_SRC} | grep '//!' | sed -E 's#^//! ?##' >> $@

.PHONY : preview
preview: docs/cmdline.md
	gh markdown-preview docs/cmdline.md
