#!/bin/bash
# Copyright 2019 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Runs *_unittest.py modules.

set -e

# Invoke unit test scripts.
for unittest_script in *_unittest.py; do
  echo "Running ${unittest_script}"
  ./${unittest_script} || break
done
