#!/bin/bash

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# TODO: Delete after ~May 2018.
exec cat << EOF
$0 has been replaced with 'cros_gdb'.  Please update your workflow and
file any bugs about missing functionality at https://crbug.com/new.
EOF
