#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Start the Dev Server after making sure we are running under a chroot.
. /usr/lib/crosutils/common.sh || exit 1

# Script must be run inside the chroot if not in 'always serve' mode.
if [[ "$1" != "--archive_dir" ]]; then
  restart_in_chroot_if_needed "$@"
fi

export DEFAULT_INSTALL_MASK

# Trap various signals.
trap 'trap_flag=1' INT TERM QUIT

# Spawn devserver in the background, record its pid.
if [ -f /usr/lib/devserver/devserver.py ]; then
  python /usr/lib/devserver/devserver.py "$@" &
else
  python /usr/bin/devserver.py "$@" &
fi
devserver_pid=$!

# Wait for devserver to die, or a signal.
wait

# If interrupted by signal, kill the devserver.
if [ -n "${trap_flag}" ]; then
  kill ${devserver_pid}
fi
