# Copyright 2021 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Use servod docker image maintained by HWTools.
# In case of access issues, contact haddowk@ or HWTools team.
FROM us-docker.pkg.dev/chromeos-hw-tools/servod/servod:release

COPY cros-servod /usr/bin/cros-servod
