#!/bin/bash
#
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.


FINDMISSING_DIR="$(cd $(dirname $0); pwd)"

cd "${FINDMISSING_DIR}"
if [[ ! -e env/bin/activate ]]; then
    echo "Environment is not set up to run findmissing client."
    echo "Please run: ./scripts/local/local_database_setup.sh and repeat this command"
    exit 1
fi

source env/bin/activate

# Run findmissing script with parameters in virtual env
./findmissing.py "$@"
