#!/usr/bin/env python3
# -*- coding: utf-8 -*-"
#
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Module containing methods interfacing with git

i.e Parsing git logs for change-id, full commit sha's, etc.
"""

from __future__ import print_function
import os
import re
import subprocess
import common


def get_upstream_fullsha(abbrev_sha):
    """Returns the full upstream sha for an abbreviated 12 digit sha using git cli"""
    upstream_absolute_path = common.get_kernel_absolute_path(common.UPSTREAM_PATH)
    try:
        cmd = ['git', '-C', upstream_absolute_path, 'rev-parse', abbrev_sha]
        full_sha = subprocess.check_output(cmd).decode('utf-8')
        return full_sha.rstrip()
    except subprocess.CalledProcessError as e:
        raise type(e)('Could not find full upstream sha for %s' % abbrev_sha, e.cmd) from e


def get_upstream_commit_message(upstream_sha):
    """Returns the commit message for a given upstream sha using git cli."""
    upstream_absolute_path = common.get_kernel_absolute_path(common.UPSTREAM_PATH)
    try:
        cmd = ['git', '-C', upstream_absolute_path, 'log',
                '--format=%B', '-n', '1', upstream_sha]
        commit_message = subprocess.check_output(cmd).decode('utf-8', errors='ignore')
        return commit_message
    except subprocess.CalledProcessError as e:
        raise type(e)('Couldnt retrieve commit for upstream sha %s'
                        % upstream_sha, e.cmd) from e


def get_commit_changeid_linux_chrome(kernel_sha):
    """Returns the changeid of the most recent local commit by parsing linux_chrome git log."""
    chrome_absolute_path = common.get_kernel_absolute_path(common.CHROMEOS_PATH)
    try:
        cmd = ['git', '-C', chrome_absolute_path, 'log', '--format=%B', '-n', '1', kernel_sha]
        commit_message = subprocess.check_output(cmd).decode('utf-8', errors='ignore')

        m = re.findall('^Change-Id: (I[a-z0-9]{40})$', commit_message, re.M)

        # Get last change-id in case chrome sha cherry-picked/reverted into new commit
        return m[-1]
    except subprocess.CalledProcessError as e:
        raise type(e)('Couldnt retrieve changeid for most recent local commit', e.cmd) from e
    except IndexError as e:
        raise type(e)('Did not find Change-Id line for linux chrome sha %s' % kernel_sha) from e


def get_last_commit_sha_linux_chrome():
    """Retrieves the last SHA in linux_chrome repository."""
    chrome_absolute_path = common.get_kernel_absolute_path(common.CHROMEOS_PATH)
    try:
        cmd = ['git', '-C', chrome_absolute_path, 'rev-parse', 'HEAD']
        last_commit = subprocess.check_output(cmd).decode('utf-8')
        return last_commit.rstrip()
    except subprocess.CalledProcessError as e:
        raise type(e)('Couldnt retrieve most recent commit in linux_chrome', e.cmd) from e


def cherry_pick_and_push_fix(fixer_upstream_sha, chromeos_branch, fix_commit_message):
    """Cherry picks upstream commit into chrome repo."""
    cwd = os.getcwd()
    chrome_absolute_path = common.get_kernel_absolute_path(common.CHROMEOS_PATH)

    # reset linux_chrome repo to remove local changes
    try:
        os.chdir(chrome_absolute_path)
        subprocess.run(['git', 'checkout', chromeos_branch])
        subprocess.run(['git', 'reset', '--hard', 'origin/%s' % chromeos_branch])
        subprocess.run(['git', 'cherry-pick', '-n', fixer_upstream_sha])
        subprocess.run(['git', 'commit', '-s', '-m', fix_commit_message])

        # commit has been cherry-picked and committed locally, precommit hook
        #  in git repository adds changeid to the commit message
        last_commit = get_last_commit_sha_linux_chrome()
        fixer_changeid = get_commit_changeid_linux_chrome(last_commit)

        subprocess.run(['git', 'push', 'origin',
                            'HEAD:refs/for/%s%%t=autogenerated' % chromeos_branch])
        subprocess.run(['git', 'reset', '--hard', 'origin/%s' % chromeos_branch])

        return fixer_changeid
    except subprocess.CalledProcessError as e:
        raise ValueError('Failed to cherrypick and push upstream fix %s on branch %s'
                        % (fixer_upstream_sha, chromeos_branch)) from e
    finally:
        subprocess.run(['git', 'reset', '--hard', 'origin/%s' % chromeos_branch])
        os.chdir(cwd)
