# Copyright 2022 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM ubuntu:bionic
COPY fw-provision /usr/bin/fw-provision
COPY fw-config.json /usr/share/ap_firmware_config/fw-config.json
